name: diamonds
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - backcall=0.2.0
  - ca-certificates=2024.2.2
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - packaging=24.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.9.19
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pywin32=305
  - pyzmq=25.1.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tornado=6.2
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wcwidth=0.2.13
  - wheel=0.43.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - altair==5.3.0
      - attrs==23.2.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.53.0
      - fsspec==2024.5.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.23.2
      - idna==3.7
      - importlib-resources==6.4.0
      - intel-openmp==2021.4.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mkl==2021.4.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - pandas==2.2.2
      - pillow==10.3.0
      - plotly==5.22.0
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pydeck==0.9.1
      - pyparsing==3.1.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - smmap==5.0.1
      - streamlit==1.35.0
      - sympy==1.12.1
      - tbb==2021.12.0
      - tenacity==8.3.0
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - toolz==0.12.1
      - torch==2.3.0
      - tqdm==4.66.4
      - transformers==4.41.2
      - tzdata==2024.1
      - urllib3==2.2.1
      - watchdog==4.0.1
